[package]
name = "bdf_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.35"
reqwest = { version = "0.12.12", features = ["blocking"] }
